package com.talent.hibernate;

import java.util.Date;


/**
 * ClassVO generated by MyEclipse - Hibernate Tools
 */

public class ClassVO  implements java.io.Serializable {


    // Fields    

     private Integer classId;
     private Integer classTypeId;
     private String className;
     private String classShortName;
     private String prefix;
     private String commission;
     private Integer headTeacherId;
     private Integer recruitNum;
     private Integer factNum;
     private String kaoChaStand;
     private String xueZhi;
     private String xueRi;
     private String otherMoney;
     private Date regTime;
     private Date reachTime;
     private Date beginTime;
     private Date endTime;
     private Date ThesisDeadline;
     private String classroomId;
     private String buildingId;
     private Integer repastTypeId;
     private Integer deposit;
     private Integer isArrangedDorm;
     private String repastStand;
     private String educatStand;
     private String teacherString;
     private String remark;
     private Integer enable;
     private Integer makeLinkBook;
     private Integer makeStuBook;
     private Integer isHistoryClass;
     private String repastCard;
     private String exploreCost;
     private Integer levelId;
     private String classCode;
     private Integer isUnitEva;
     private Integer IsWebEva;
     private Integer buyNewspaper;
     private Integer takePhoto;
     private Integer regRoom;
     private String proName;
     private String renShiNo;
     private byte isNews;


    // Constructors

    /** default constructor */
    public ClassVO() {
    }

	/** minimal constructor */
    public ClassVO(Integer deposit, Integer isArrangedDorm, Integer enable) {
        this.deposit = deposit;
        this.isArrangedDorm = isArrangedDorm;
        this.enable = enable;
    }
    
    public ClassVO(String className, Integer isHistoryClass) {
	this.className = className;
	this.isHistoryClass = isHistoryClass;
    }
    
    /** full constructor */
    public ClassVO(Integer classTypeId, String className, String classShortName, String prefix, String commission, Integer headTeacherId, Integer recruitNum, Integer factNum, String kaoChaStand, String xueZhi, String xueRi, String otherMoney, Date regTime, Date reachTime, Date beginTime, Date endTime, Date ThesisDeadline,String classroomId, String buildingId, Integer repastTypeId, Integer deposit, Integer isArrangedDorm, String repastStand, String educatStand, String teacherString, String remark, Integer enable, Integer makeLinkBook, Integer makeStuBook, Integer isHistoryClass, String repastCard, String exploreCost, Integer levelId) {
        this.classTypeId = classTypeId;
        this.className = className;
        this.classShortName = classShortName;
        this.prefix = prefix;
        this.commission = commission;
        this.headTeacherId = headTeacherId;
        this.recruitNum = recruitNum;
        this.factNum = factNum;
        this.kaoChaStand = kaoChaStand;
        this.xueZhi = xueZhi;
        this.xueRi = xueRi;
        this.otherMoney = otherMoney;
        this.regTime = regTime;
        this.reachTime = reachTime;
        this.beginTime = beginTime;
        this.endTime = endTime;
        this.ThesisDeadline = ThesisDeadline;
        this.classroomId = classroomId;
        this.buildingId = buildingId;
        this.repastTypeId = repastTypeId;
        this.deposit = deposit;
        this.isArrangedDorm = isArrangedDorm;
        this.repastStand = repastStand;
        this.educatStand = educatStand;
        this.teacherString = teacherString;
        this.remark = remark;
        this.enable = enable;
        this.makeLinkBook = makeLinkBook;
        this.makeStuBook = makeStuBook;
        this.isHistoryClass = isHistoryClass;
        this.repastCard = repastCard;
        this.exploreCost = exploreCost;
        this.levelId = levelId;
    }

   
    // Property accessors

    public Integer getClassId() {
        return this.classId;
    }
    
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    public Integer getClassTypeId() {
        return this.classTypeId;
    }
    
    public void setClassTypeId(Integer classTypeId) {
        this.classTypeId = classTypeId;
    }

    public String getClassName() {
        return this.className;
    }
    
    public void setClassName(String className) {
        this.className = className;
    }

    public String getClassShortName() {
        return this.classShortName;
    }
    
    public void setClassShortName(String classShortName) {
        this.classShortName = classShortName;
    }

    public String getPrefix() {
        return this.prefix;
    }
    
    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }

    public String getCommission() {
        return this.commission;
    }
    
    public void setCommission(String commission) {
        this.commission = commission;
    }

    public Integer getHeadTeacherId() {
        return this.headTeacherId;
    }
    
    public void setHeadTeacherId(Integer headTeacherId) {
        this.headTeacherId = headTeacherId;
    }

    public Integer getRecruitNum() {
        return this.recruitNum;
    }
    
    public void setRecruitNum(Integer recruitNum) {
        this.recruitNum = recruitNum;
    }

    public Integer getFactNum() {
        return this.factNum;
    }
    
    public void setFactNum(Integer factNum) {
        this.factNum = factNum;
    }

    public String getKaoChaStand() {
        return this.kaoChaStand;
    }
    
    public void setKaoChaStand(String kaoChaStand) {
        this.kaoChaStand = kaoChaStand;
    }

    public String getXueZhi() {
        return this.xueZhi;
    }
    
    public void setXueZhi(String xueZhi) {
        this.xueZhi = xueZhi;
    }

    public String getXueRi() {
        return this.xueRi;
    }
    
    public void setXueRi(String xueRi) {
        this.xueRi = xueRi;
    }

    public String getOtherMoney() {
        return this.otherMoney;
    }
    
    public void setOtherMoney(String otherMoney) {
        this.otherMoney = otherMoney;
    }

    public Date getRegTime() {
        return this.regTime;
    }
    
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    public Date getReachTime() {
        return this.reachTime;
    }
    
    public void setReachTime(Date reachTime) {
        this.reachTime = reachTime;
    }

    public Date getBeginTime() {
        return this.beginTime;
    }
    
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public Date getThesisDeadline() {
        return this.ThesisDeadline;
    }
    
    public void setThesisDeadline(Date thesisDeadline) {
        this.ThesisDeadline = thesisDeadline;
    }

    public String getClassroomId() {
        return this.classroomId;
    }
    
    public void setClassroomId(String classroomId) {
        this.classroomId = classroomId;
    }

    public String getBuildingId() {
        return this.buildingId;
    }
    
    public void setBuildingId(String buildingId) {
        this.buildingId = buildingId;
    }

    public Integer getRepastTypeId() {
        return this.repastTypeId;
    }
    
    public void setRepastTypeId(Integer repastTypeId) {
        this.repastTypeId = repastTypeId;
    }

    public Integer getDeposit() {
        return this.deposit;
    }
    
    public void setDeposit(Integer deposit) {
        this.deposit = deposit;
    }

    public Integer getIsArrangedDorm() {
        return this.isArrangedDorm;
    }
    
    public void setIsArrangedDorm(Integer isArrangedDorm) {
        this.isArrangedDorm = isArrangedDorm;
    }

    public String getRepastStand() {
        return this.repastStand;
    }
    
    public void setRepastStand(String repastStand) {
        this.repastStand = repastStand;
    }

    public String getEducatStand() {
        return this.educatStand;
    }
    
    public void setEducatStand(String educatStand) {
        this.educatStand = educatStand;
    }

    public String getTeacherString() {
        return this.teacherString;
    }
    
    public void setTeacherString(String teacherString) {
        this.teacherString = teacherString;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Integer getEnable() {
        return this.enable;
    }
    
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    public Integer getMakeLinkBook() {
        return this.makeLinkBook;
    }
    
    public void setMakeLinkBook(Integer makeLinkBook) {
        this.makeLinkBook = makeLinkBook;
    }

    public Integer getMakeStuBook() {
        return this.makeStuBook;
    }
    
    public void setMakeStuBook(Integer makeStuBook) {
        this.makeStuBook = makeStuBook;
    }

    public Integer getIsHistoryClass() {
        return this.isHistoryClass;
    }
    
    public void setIsHistoryClass(Integer isHistoryClass) {
        this.isHistoryClass = isHistoryClass;
    }

    public String getRepastCard() {
        return this.repastCard;
    }
    
    public void setRepastCard(String repastCard) {
        this.repastCard = repastCard;
    }

    public String getExploreCost() {
        return this.exploreCost;
    }
    
    public void setExploreCost(String exploreCost) {
        this.exploreCost = exploreCost;
    }

    public Integer getLevelId() {
        return this.levelId;
    }
    
    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }

    public String getClassCode() {
        return classCode;
    }

    public void setClassCode(String classCode) {
        this.classCode = classCode;
    }

    public Integer getBuyNewspaper() {
        return buyNewspaper;
    }

    public void setBuyNewspaper(Integer buyNewspaper) {
        this.buyNewspaper = buyNewspaper;
    }

    public byte getIsNews() {
        return isNews;
    }

    public void setIsNews(byte isNews) {
        this.isNews = isNews;
    }

    public Integer getIsUnitEva() {
        return isUnitEva;
    }

    public void setIsUnitEva(Integer isUnitEva) {
        this.isUnitEva = isUnitEva;
    }

    public Integer getIsWebEva() {
        return IsWebEva;
    }

    public void setIsWebEva(Integer isWebEva) {
        IsWebEva = isWebEva;
    }

    public String getProName() {
        return proName;
    }

    public void setProName(String proName) {
        this.proName = proName;
    }

    public Integer getRegRoom() {
        return regRoom;
    }

    public void setRegRoom(Integer regRoom) {
        this.regRoom = regRoom;
    }

    public String getRenShiNo() {
        return renShiNo;
    }

    public void setRenShiNo(String renShiNo) {
        this.renShiNo = renShiNo;
    }

    public Integer getTakePhoto() {
        return takePhoto;
    }

    public void setTakePhoto(Integer takePhoto) {
        this.takePhoto = takePhoto;
    }
   








}