package com.talent.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * ClassSubject generated by MyEclipse - Hibernate Tools
 */

public class ClassSubject implements java.io.Serializable {


    // Fields    

     private Integer subjectId;
     private Integer classId;
     private String subject;
     private Integer subjectNo;
     private Integer subjectType;
     private Integer scoreMethod;
     private Integer classHours;
     private String defaultScore;
     private byte isNews;
     private Set scores = new HashSet(0);


    // Constructors

    /** default constructor */
    public ClassSubject() {
    }

	/** minimal constructor */
    public ClassSubject(Integer subjectId) {
        this.subjectId = subjectId;
    }
    
    /** full constructor */
    public ClassSubject(Integer subjectId, Integer classId, String subject, Integer subjectNo, Integer subjectType, Integer scoreMethod, Integer classHours, String defaultScore, byte isNews, Set scores) {
        this.subjectId = subjectId;
        this.classId = classId;
        this.subject = subject;
        this.subjectNo = subjectNo;
        this.subjectType = subjectType;
        this.scoreMethod = scoreMethod;
        this.classHours = classHours;
        this.defaultScore = defaultScore;
        this.isNews = isNews;
        this.scores = scores;
    }

   
    // Property accessors

    public Integer getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    public Integer getClassId() {
        return this.classId;
    }
    
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    public Integer getSubjectNo() {
        return this.subjectNo;
    }
    
    public void setSubjectNo(Integer subjectNo) {
        this.subjectNo = subjectNo;
    }

    public Integer getSubjectType() {
        return this.subjectType;
    }
    
    public void setSubjectType(Integer subjectType) {
        this.subjectType = subjectType;
    }

    public Integer getScoreMethod() {
        return this.scoreMethod;
    }
    
    public void setScoreMethod(Integer scoreMethod) {
        this.scoreMethod = scoreMethod;
    }

    public Integer getClassHours() {
        return this.classHours;
    }
    
    public void setClassHours(Integer classHours) {
        this.classHours = classHours;
    }

    public String getDefaultScore() {
        return this.defaultScore;
    }
    
    public void setDefaultScore(String defaultScore) {
        this.defaultScore = defaultScore;
    }

    public byte getIsNews() {
        return this.isNews;
    }
    
    public void setIsNews(byte isNews) {
        this.isNews = isNews;
    }

    public Set getScores() {
        return this.scores;
    }
    
    public void setScores(Set scores) {
        this.scores = scores;
    }
   








}