package com.talent.hibernate;

import java.util.Date;


/**
 * CourseAdjust generated by MyEclipse - Hibernate Tools
 */

public class CourseAdjust  implements java.io.Serializable {


    // Fields    

     private Integer adjustId;
     private Integer planId;
     private Integer classId;
     private Integer courseId;
     private Date adjustTime;
     private String adjuster;
     private String adjustContent;
     private Integer isSendNotice;
     private String noticeMethod;
     private Date noticeTime;
     private Integer noticeNum;
     private Date endTime;
     private Integer isHaveHandled;
     private Integer classroomId;
     private Integer deleteFlag;
     private String adjusterName;
     private String tzDate; //调整日期
     private String tzTime; //调整时间
     private String fbDate; //发布时间
     private String fbMethod; //发布方法

    // Constructors

    /** default constructor */
    public CourseAdjust() {
    }

	/** minimal constructor */
    public CourseAdjust(Integer adjustId) {
        this.adjustId = adjustId;
    }
    
    /** full constructor */
    public CourseAdjust(Integer adjustId, Integer planId, Integer classId, Integer courseId, Date adjustTime, String adjuster, String adjustContent, Integer isSendNotice, String noticeMethod, Date noticeTime, Integer noticeNum, Date endTime, Integer isHaveHandled, Integer classroomId, Integer deleteFlag) {
        this.adjustId = adjustId;
        this.planId = planId;
        this.classId = classId;
        this.courseId = courseId;
        this.adjustTime = adjustTime;
        this.adjuster = adjuster;
        this.adjustContent = adjustContent;
        this.isSendNotice = isSendNotice;
        this.noticeMethod = noticeMethod;
        this.noticeTime = noticeTime;
        this.noticeNum = noticeNum;
        this.endTime = endTime;
        this.isHaveHandled = isHaveHandled;
        this.classroomId = classroomId;
        this.deleteFlag = deleteFlag;

    }

   
    // Property accessors

    public Integer getAdjustId() {
        return this.adjustId;
    }
    
    public void setAdjustId(Integer adjustId) {
        this.adjustId = adjustId;
    }

    public Integer getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    public Integer getClassId() {
        return this.classId;
    }
    
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    public Integer getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    public Date getAdjustTime() {
        return this.adjustTime;
    }
    
    public void setAdjustTime(Date adjustTime) {
        this.adjustTime = adjustTime;
    }

    public String getAdjuster() {
        return this.adjuster;
    }
    
    public void setAdjuster(String adjuster) {
        this.adjuster = adjuster;
    }

    public String getAdjustContent() {
        return this.adjustContent;
    }
    
    public void setAdjustContent(String adjustContent) {
        this.adjustContent = adjustContent;
    }

    public Integer getIsSendNotice() {
        return this.isSendNotice;
    }
    
    public void setIsSendNotice(Integer isSendNotice) {
        this.isSendNotice = isSendNotice;
    }

    public String getNoticeMethod() {
        return this.noticeMethod;
    }
    
    public void setNoticeMethod(String noticeMethod) {
        this.noticeMethod = noticeMethod;
    }

    public Date getNoticeTime() {
        return this.noticeTime;
    }
    
    public void setNoticeTime(Date noticeTime) {
        this.noticeTime = noticeTime;
    }

    public Integer getNoticeNum() {
        return this.noticeNum;
    }
    
    public void setNoticeNum(Integer noticeNum) {
        this.noticeNum = noticeNum;
    }

    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public Integer getIsHaveHandled() {
        return this.isHaveHandled;
    }
    
    public void setIsHaveHandled(Integer isHaveHandled) {
        this.isHaveHandled = isHaveHandled;
    }

    public Integer getClassroomId() {
        return this.classroomId;
    }
    
    public void setClassroomId(Integer classroomId) {
        this.classroomId = classroomId;
    }

    public Integer getDeleteFlag() {
        return this.deleteFlag;
    }
    
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }


   
    public String getAdjusterName() {
        return this.adjusterName;
    }
    
    public void setAdjusterName(String adjusterName) {
        this.adjusterName = adjusterName;
    }


    public String getTzDate() {
        return this.tzDate;
    }
    
    public void setTzDate(String tzDate) {
        this.tzDate = tzDate;
    }
    public String getTzTime() {
        return this.tzTime;
    }
    
    public void setTzTime(String tzTime) {
        this.tzTime = tzTime;
    }
    public String getFbDate() {
        return this.fbDate;
    }
    
    public void setFbDate(String fbDate) {
        this.fbDate = fbDate;
    }
    public String getFbMethod() {
        return this.fbMethod;
    }
    
    public void setFbMethod(String fbMethod) {
        this.fbMethod = fbMethod;
    }




}