package com.talent.hibernate;

import java.util.HashSet;
import java.util.Set;


/**
 * Eosoperator generated by MyEclipse - Hibernate Tools
 */

public class Eosoperator  implements java.io.Serializable {


    // Fields    

     private Integer operatorId;
     private String isLocal;
     private String operatorName;
     private String password;
     private Integer status;
     private String userId;
     private Integer userTypeId;
     private String cardId;
     private Integer operatorType;
     private Set eosorgTEmployees = new HashSet(0);
     private Set eosoperatorRoles = new HashSet(0);
     private Set eosorgTOrganizations = new HashSet(0);
     private Set eosorgTEmpOrgRefs = new HashSet(0);


    // Constructors

    /** default constructor */
    public Eosoperator() {
    }

	/** minimal constructor */
    public Eosoperator(String userId) {
        this.userId = userId;
    }
    
    /** full constructor */
    public Eosoperator(String isLocal, String operatorName, String password, Integer status, String userId, Integer userTypeId, String cardId, Integer operatorType, Set eosorgTEmployees, Set eosoperatorRoles, Set eosorgTOrganizations, Set eosorgTEmpOrgRefs) {
        this.isLocal = isLocal;
        this.operatorName = operatorName;
        this.password = password;
        this.status = status; 
        this.userId = userId;
        this.userTypeId = userTypeId;
        this.cardId = cardId;
        this.operatorType = operatorType;
        this.eosorgTEmployees = eosorgTEmployees;
        this.eosoperatorRoles = eosoperatorRoles;
        this.eosorgTOrganizations = eosorgTOrganizations;
        this.eosorgTEmpOrgRefs = eosorgTEmpOrgRefs;
    }

   
    // Property accessors

    public Integer getOperatorId() {
        return this.operatorId;
    }
    
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    public String getIsLocal() {
        return this.isLocal;
    }
    
    public void setIsLocal(String isLocal) {
        this.isLocal = isLocal;
    }

    public String getOperatorName() {
        return this.operatorName;
    }
    
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    public Integer getUserTypeId() {
        return this.userTypeId;
    }
    
    public void setUserTypeId(Integer userTypeId) {
        this.userTypeId = userTypeId;
    }

    public String getCardId() {
        return this.cardId;
    }
    
    public void setCardId(String cardId) {
        this.cardId = cardId;
    }

    public Integer getOperatorType() {
        return this.operatorType;
    }
    
    public void setOperatorType(Integer operatorType) {
        this.operatorType = operatorType;
    }

    public Set getEosorgTEmployees() {
        return this.eosorgTEmployees;
    }
    
    public void setEosorgTEmployees(Set eosorgTEmployees) {
        this.eosorgTEmployees = eosorgTEmployees;
    }

    public Set getEosoperatorRoles() {
        return this.eosoperatorRoles;
    }
    
    public void setEosoperatorRoles(Set eosoperatorRoles) {
        this.eosoperatorRoles = eosoperatorRoles;
    }

    public Set getEosorgTOrganizations() {
        return this.eosorgTOrganizations;
    }
    
    public void setEosorgTOrganizations(Set eosorgTOrganizations) {
        this.eosorgTOrganizations = eosorgTOrganizations;
    }

    public Set getEosorgTEmpOrgRefs() {
        return this.eosorgTEmpOrgRefs;
    }
    
    public void setEosorgTEmpOrgRefs(Set eosorgTEmpOrgRefs) {
        this.eosorgTEmpOrgRefs = eosorgTEmpOrgRefs;
    }
   








}