package com.talent.hibernate;

import java.util.Date;


/**
 * News generated by MyEclipse - Hibernate Tools
 */

public class News  implements java.io.Serializable {


    // Fields    

     private Integer newsId;
     private String title;
     private String content;
     private String columns;
     private Integer publisher;
     private String publisherName;
     private String department;
     private Date publishDate;
     private String subhead;


    // Constructors

    /** default constructor */
    public News() {
    }

	/** minimal constructor */
    public News(String title, String content, String columns, Integer publisher) {
        this.title = title;
        this.content = content;
        this.columns = columns;
        this.publisher = publisher;
    }
    
    /** full constructor */
    public News(String title, String content, String columns, Integer publisher, String publisherName, String department, Date publishDate, String subhead) {
        this.title = title;
        this.content = content;
        this.columns = columns;
        this.publisher = publisher;
        this.publisherName = publisherName;
        this.department = department;
        this.publishDate = publishDate;
        this.subhead = subhead;
    }

   
    // Property accessors

    public Integer getNewsId() {
        return this.newsId;
    }
    
    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    public String getColumns() {
        return this.columns;
    }
    
    public void setColumns(String columns) {
        this.columns = columns;
    }

    public Integer getPublisher() {
        return this.publisher;
    }
    
    public void setPublisher(Integer publisher) {
        this.publisher = publisher;
    }

    public String getPublisherName() {
        return this.publisherName;
    }
    
    public void setPublisherName(String publisherName) {
        this.publisherName = publisherName;
    }

    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }

    public Date getPublishDate() {
        return this.publishDate;
    }
    
    public void setPublishDate(Date publishDate) {
        this.publishDate = publishDate;
    }

    public String getSubhead() {
        return this.subhead;
    }
    
    public void setSubhead(String subhead) {
        this.subhead = subhead;
    }
   








}