package com.talent.hibernate;



/**
 * Room generated by MyEclipse - Hibernate Tools
 */

public class Room  implements java.io.Serializable {


    // Fields    

     private Integer roomId;
     private Integer roomTypeId;
     private Integer buildingId;
     private Integer layerNo;
     private String roomName;
     private Integer seatNum;
     private String tel;
     private String potid;
     private Integer price1;
     private Integer price2;
     private Integer price3;
     private Integer price4;
     private Integer state;
     private Integer flag;
     private Integer controlerId;
     private Integer readerId;
     private Integer leftflag;
     private byte enable;


    // Constructors

    /** default constructor */
    public Room() {
    }

	/** minimal constructor */
    public Room(Integer roomId, byte enable) {
        this.roomId = roomId;
        this.enable = enable;
    }
    
    /** full constructor */
    public Room(Integer roomId, Integer roomTypeId, Integer buildingId, Integer layerNo, String roomName, Integer seatNum, String tel, String potid, Integer price1, Integer price2, Integer price3, Integer price4, Integer state, Integer flag, Integer controlerId, Integer readerId, Integer leftflag, byte enable) {
        this.roomId = roomId;
        this.roomTypeId = roomTypeId;
        this.buildingId = buildingId;
        this.layerNo = layerNo;
        this.roomName = roomName;
        this.seatNum = seatNum;
        this.tel = tel;
        this.potid = potid;
        this.price1 = price1;
        this.price2 = price2;
        this.price3 = price3;
        this.price4 = price4;
        this.state = state;
        this.flag = flag;
        this.controlerId = controlerId;
        this.readerId = readerId;
        this.leftflag = leftflag;
        this.enable = enable;
    }

   
    // Property accessors

    public Integer getRoomId() {
        return this.roomId;
    }
    
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    public Integer getRoomTypeId() {
        return this.roomTypeId;
    }
    
    public void setRoomTypeId(Integer roomTypeId) {
        this.roomTypeId = roomTypeId;
    }

    public Integer getBuildingId() {
        return this.buildingId;
    }
    
    public void setBuildingId(Integer buildingId) {
        this.buildingId = buildingId;
    }

    public Integer getLayerNo() {
        return this.layerNo;
    }
    
    public void setLayerNo(Integer layerNo) {
        this.layerNo = layerNo;
    }

    public String getRoomName() {
        return this.roomName;
    }
    
    public void setRoomName(String roomName) {
        this.roomName = roomName;
    }

    public Integer getSeatNum() {
        return this.seatNum;
    }
    
    public void setSeatNum(Integer seatNum) {
        this.seatNum = seatNum;
    }

    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getPotid() {
        return this.potid;
    }
    
    public void setPotid(String potid) {
        this.potid = potid;
    }

    public Integer getPrice1() {
        return this.price1;
    }
    
    public void setPrice1(Integer price1) {
        this.price1 = price1;
    }

    public Integer getPrice2() {
        return this.price2;
    }
    
    public void setPrice2(Integer price2) {
        this.price2 = price2;
    }

    public Integer getPrice3() {
        return this.price3;
    }
    
    public void setPrice3(Integer price3) {
        this.price3 = price3;
    }

    public Integer getPrice4() {
        return this.price4;
    }
    
    public void setPrice4(Integer price4) {
        this.price4 = price4;
    }

    public Integer getState() {
        return this.state;
    }
    
    public void setState(Integer state) {
        this.state = state;
    }

    public Integer getFlag() {
        return this.flag;
    }
    
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    public Integer getControlerId() {
        return this.controlerId;
    }
    
    public void setControlerId(Integer controlerId) {
        this.controlerId = controlerId;
    }

    public Integer getReaderId() {
        return this.readerId;
    }
    
    public void setReaderId(Integer readerId) {
        this.readerId = readerId;
    }

    public Integer getLeftflag() {
        return this.leftflag;
    }
    
    public void setLeftflag(Integer leftflag) {
        this.leftflag = leftflag;
    }

    public byte getEnable() {
        return this.enable;
    }
    
    public void setEnable(byte enable) {
        this.enable = enable;
    }
   








}