package com.talent.hibernate;



/**
 * ScoreType generated by MyEclipse - Hibernate Tools
 */

public class ScoreType  implements java.io.Serializable {


    // Fields    

     private Integer scoretypeid;
     private String scoretypename;


    // Constructors

    /** default constructor */
    public ScoreType() {
    }

    
    /** full constructor */
    public ScoreType(String scoretypename) {
        this.scoretypename = scoretypename;
    }

   
    // Property accessors

    public Integer getScoretypeid() {
        return this.scoretypeid;
    }
    
    public void setScoretypeid(Integer scoretypeid) {
        this.scoretypeid = scoretypeid;
    }

    public String getScoretypename() {
        return this.scoretypename;
    }
    
    public void setScoretypename(String scoretypename) {
        this.scoretypename = scoretypename;
    }
   








}