package com.talent.hibernate;



/**
 * Score generated by MyEclipse - Hibernate Tools
 */

public class Score implements java.io.Serializable {


    // Fields    

     private Integer scoreId;
     private Student student;
     private ClassSubject classSubject;
     private String score;
     private byte isNews;


    // Constructors

    /** default constructor */
    public Score() {
    }

	/** minimal constructor */
    public Score(Integer scoreId) {
        this.scoreId = scoreId;
    }
    
    /** full constructor */
    public Score(Integer scoreId, Student student, ClassSubject classSubject, String score, byte isNews) {
        this.scoreId = scoreId;
        this.student = student;
        this.classSubject = classSubject;
        this.score = score;
        this.isNews = isNews;
    }

   
    // Property accessors

    public Integer getScoreId() {
        return this.scoreId;
    }
    
    public void setScoreId(Integer scoreId) {
        this.scoreId = scoreId;
    }

    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

    public ClassSubject getClassSubject() {
        return this.classSubject;
    }
    
    public void setClassSubject(ClassSubject classSubject) {
        this.classSubject = classSubject;
    }

    public String getScore() {
        return this.score;
    }
    
    public void setScore(String score) {
        this.score = score;
    }

    public byte getIsNews() {
        return this.isNews;
    }
    
    public void setIsNews(byte isNews) {
        this.isNews = isNews;
    }
   








}