package com.talent.hibernate;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Student generated by MyEclipse - Hibernate Tools
 */

public class Student implements java.io.Serializable {


    // Fields    

     private Integer studentId;
     private Integer classId;
     private Integer teamId;
     private String seatNo;
     private Integer folkId;
     private Integer degreeId;
     private Date startWorkingTime;
     private Date joinPartyTime;
     private String workingOrgan;
     private String duty;
     private String organTel;
     private String homeTel;
     private String mobileTel;
     private String diplomaNo;
     private Integer roomId;
     private Integer absenceTimes;
     private Integer absenceHowLong;
     private Integer truantTimes;
     private String photo;
     private String photoid;
     private String email;
     private String remark;
     private byte isCheck;
     private Integer dutylevel;
     private String major;
     private Integer isleader;
     private Integer orderno;
     private String studentNo;
     private String sex;
     private Date birthdate;
     private String firstchar;
     private String barcode;
     private Integer isQuit;
     private Date quitTime;
     private String quitReason;
     private String nativePlace;
     private String eduLevel;
     private String jobTitle;
     private String partyPost;
     private String societyPost;
     private String orgAddr;
     private String orgPostcode;
     private byte isNews;
     private Set scores = new HashSet(0);


    // Constructors

    /** default constructor */
    public Student() {
    }

	/** minimal constructor */
    public Student(Integer studentId) {
        this.studentId = studentId;
    }
    
    /** full constructor */
    public Student(Integer studentId, Integer classId, Integer teamId, String seatNo, Integer folkId, Integer degreeId, Date startWorkingTime, Date joinPartyTime, String workingOrgan, String duty, String organTel, String homeTel, String mobileTel, String diplomaNo, Integer roomId, Integer absenceTimes, Integer absenceHowLong, Integer truantTimes, String photo, String photoid, String email, String remark, byte isCheck, Integer dutylevel, String major, Integer isleader, Integer orderno, String studentNo, String sex, Date birthdate, String firstchar, String barcode, Integer isQuit, Date quitTime, String quitReason, String nativePlace, String eduLevel, String jobTitle, String partyPost, String societyPost, String orgAddr, String orgPostcode, byte isNews, Set scores) {
        this.studentId = studentId;
        this.classId = classId;
        this.teamId = teamId;
        this.seatNo = seatNo;
        this.folkId = folkId;
        this.degreeId = degreeId;
        this.startWorkingTime = startWorkingTime;
        this.joinPartyTime = joinPartyTime;
        this.workingOrgan = workingOrgan;
        this.duty = duty;
        this.organTel = organTel;
        this.homeTel = homeTel;
        this.mobileTel = mobileTel;
        this.diplomaNo = diplomaNo;
        this.roomId = roomId;
        this.absenceTimes = absenceTimes;
        this.absenceHowLong = absenceHowLong;
        this.truantTimes = truantTimes;
        this.photo = photo;
        this.photoid = photoid;
        this.email = email;
        this.remark = remark;
        this.isCheck = isCheck;
        this.dutylevel = dutylevel;
        this.major = major;
        this.isleader = isleader;
        this.orderno = orderno;
        this.studentNo = studentNo;
        this.sex = sex;
        this.birthdate = birthdate;
        this.firstchar = firstchar;
        this.barcode = barcode;
        this.isQuit = isQuit;
        this.quitTime = quitTime;
        this.quitReason = quitReason;
        this.nativePlace = nativePlace;
        this.eduLevel = eduLevel;
        this.jobTitle = jobTitle;
        this.partyPost = partyPost;
        this.societyPost = societyPost;
        this.orgAddr = orgAddr;
        this.orgPostcode = orgPostcode;
        this.isNews = isNews;
        this.scores = scores;
    }

   
    // Property accessors

    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    public Integer getClassId() {
        return this.classId;
    }
    
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    public Integer getTeamId() {
        return this.teamId;
    }
    
    public void setTeamId(Integer teamId) {
        this.teamId = teamId;
    }

    public String getSeatNo() {
        return this.seatNo;
    }
    
    public void setSeatNo(String seatNo) {
        this.seatNo = seatNo;
    }

    public Integer getFolkId() {
        return this.folkId;
    }
    
    public void setFolkId(Integer folkId) {
        this.folkId = folkId;
    }

    public Integer getDegreeId() {
        return this.degreeId;
    }
    
    public void setDegreeId(Integer degreeId) {
        this.degreeId = degreeId;
    }

    public Date getStartWorkingTime() {
        return this.startWorkingTime;
    }
    
    public void setStartWorkingTime(Date startWorkingTime) {
        this.startWorkingTime = startWorkingTime;
    }

    public Date getJoinPartyTime() {
        return this.joinPartyTime;
    }
    
    public void setJoinPartyTime(Date joinPartyTime) {
        this.joinPartyTime = joinPartyTime;
    }

    public String getWorkingOrgan() {
        return this.workingOrgan;
    }
    
    public void setWorkingOrgan(String workingOrgan) {
        this.workingOrgan = workingOrgan;
    }

    public String getDuty() {
        return this.duty;
    }
    
    public void setDuty(String duty) {
        this.duty = duty;
    }

    public String getOrganTel() {
        return this.organTel;
    }
    
    public void setOrganTel(String organTel) {
        this.organTel = organTel;
    }

    public String getHomeTel() {
        return this.homeTel;
    }
    
    public void setHomeTel(String homeTel) {
        this.homeTel = homeTel;
    }

    public String getMobileTel() {
        return this.mobileTel;
    }
    
    public void setMobileTel(String mobileTel) {
        this.mobileTel = mobileTel;
    }

    public String getDiplomaNo() {
        return this.diplomaNo;
    }
    
    public void setDiplomaNo(String diplomaNo) {
        this.diplomaNo = diplomaNo;
    }

    public Integer getRoomId() {
        return this.roomId;
    }
    
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    public Integer getAbsenceTimes() {
        return this.absenceTimes;
    }
    
    public void setAbsenceTimes(Integer absenceTimes) {
        this.absenceTimes = absenceTimes;
    }

    public Integer getAbsenceHowLong() {
        return this.absenceHowLong;
    }
    
    public void setAbsenceHowLong(Integer absenceHowLong) {
        this.absenceHowLong = absenceHowLong;
    }

    public Integer getTruantTimes() {
        return this.truantTimes;
    }
    
    public void setTruantTimes(Integer truantTimes) {
        this.truantTimes = truantTimes;
    }

    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getPhotoid() {
        return this.photoid;
    }
    
    public void setPhotoid(String photoid) {
        this.photoid = photoid;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public byte getIsCheck() {
        return this.isCheck;
    }
    
    public void setIsCheck(byte isCheck) {
        this.isCheck = isCheck;
    }

    public Integer getDutylevel() {
        return this.dutylevel;
    }
    
    public void setDutylevel(Integer dutylevel) {
        this.dutylevel = dutylevel;
    }

    public String getMajor() {
        return this.major;
    }
    
    public void setMajor(String major) {
        this.major = major;
    }

    public Integer getIsleader() {
        return this.isleader;
    }
    
    public void setIsleader(Integer isleader) {
        this.isleader = isleader;
    }

    public Integer getOrderno() {
        return this.orderno;
    }
    
    public void setOrderno(Integer orderno) {
        this.orderno = orderno;
    }

    public String getStudentNo() {
        return this.studentNo;
    }
    
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo;
    }

    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    public String getFirstchar() {
        return this.firstchar;
    }
    
    public void setFirstchar(String firstchar) {
        this.firstchar = firstchar;
    }

    public String getBarcode() {
        return this.barcode;
    }
    
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    public Integer getIsQuit() {
        return this.isQuit;
    }
    
    public void setIsQuit(Integer isQuit) {
        this.isQuit = isQuit;
    }

    public Date getQuitTime() {
        return this.quitTime;
    }
    
    public void setQuitTime(Date quitTime) {
        this.quitTime = quitTime;
    }

    public String getQuitReason() {
        return this.quitReason;
    }
    
    public void setQuitReason(String quitReason) {
        this.quitReason = quitReason;
    }

    public String getNativePlace() {
        return this.nativePlace;
    }
    
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace;
    }

    public String getEduLevel() {
        return this.eduLevel;
    }
    
    public void setEduLevel(String eduLevel) {
        this.eduLevel = eduLevel;
    }

    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    public String getPartyPost() {
        return this.partyPost;
    }
    
    public void setPartyPost(String partyPost) {
        this.partyPost = partyPost;
    }

    public String getSocietyPost() {
        return this.societyPost;
    }
    
    public void setSocietyPost(String societyPost) {
        this.societyPost = societyPost;
    }

    public String getOrgAddr() {
        return this.orgAddr;
    }
    
    public void setOrgAddr(String orgAddr) {
        this.orgAddr = orgAddr;
    }

    public String getOrgPostcode() {
        return this.orgPostcode;
    }
    
    public void setOrgPostcode(String orgPostcode) {
        this.orgPostcode = orgPostcode;
    }

    public byte getIsNews() {
        return this.isNews;
    }
    
    public void setIsNews(byte isNews) {
        this.isNews = isNews;
    }

    public Set getScores() {
        return this.scores;
    }
    
    public void setScores(Set scores) {
        this.scores = scores;
    }
   








}