package com.talent.hibernate;

import java.util.Date;


/**
 * StudentlaterLogs generated by MyEclipse - Hibernate Tools
 */

public class StudentlaterLogs  implements java.io.Serializable {


    // Fields    

     private Integer studentlaterLogsId;
     private Integer studentId;
     private Date checkTime;
     private Integer state;
     private Integer wubie;
     private Integer singleTime;
     private Date creatTime;


    // Constructors

    /** default constructor */
    public StudentlaterLogs() {
    }

    
    /** full constructor */
    public StudentlaterLogs(Integer studentId, Date checkTime, Integer state, Integer wubie, Integer singleTime, Date creatTime) {
        this.studentId = studentId;
        this.checkTime = checkTime;
        this.state = state;
        this.wubie = wubie;
        this.singleTime = singleTime;
        this.creatTime = creatTime;
    }

   
    // Property accessors

    public Integer getStudentlaterLogsId() {
        return this.studentlaterLogsId;
    }
    
    public void setStudentlaterLogsId(Integer studentlaterLogsId) {
        this.studentlaterLogsId = studentlaterLogsId;
    }

    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    public Date getCheckTime() {
        return this.checkTime;
    }
    
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    public Integer getState() {
        return this.state;
    }
    
    public void setState(Integer state) {
        this.state = state;
    }

    public Integer getWubie() {
        return this.wubie;
    }
    
    public void setWubie(Integer wubie) {
        this.wubie = wubie;
    }

    public Integer getSingleTime() {
        return this.singleTime;
    }
    
    public void setSingleTime(Integer singleTime) {
        this.singleTime = singleTime;
    }

    public Date getCreatTime() {
        return this.creatTime;
    }
    
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }
   








}