package com.talent.hibernate;

import java.util.Date;


/**
 * Teacher generated by MyEclipse - Hibernate Tools
 */

public class Teacher  implements java.io.Serializable {


    // Fields    

     private Integer teacherId;
     private Integer departmentId;
     private Integer teacherTypeId;
     private String dutyTechnicalPost;
     private byte isRetire;
     private float money;
     private String code;
     private String persition;
     private String sex;
     private Date birthdate;
     private String firstchar;
     private String organTel;
     private String homeTel;
     private String mobileTel;
     private String email;
     private String address;


    // Constructors

    /** default constructor */
    public Teacher() {
    }

    
    /** full constructor */
    public Teacher(Integer departmentId, Integer teacherTypeId, String dutyTechnicalPost, byte isRetire, float money, String code, String persition, String sex, Date birthdate, String firstchar, String organTel, String homeTel, String mobileTel, String email, String address) {
        this.departmentId = departmentId;
        this.teacherTypeId = teacherTypeId;
        this.dutyTechnicalPost = dutyTechnicalPost;
        this.isRetire = isRetire;
        this.money = money;
        this.code = code;
        this.persition = persition;
        this.sex = sex;
        this.birthdate = birthdate;
        this.firstchar = firstchar;
        this.organTel = organTel;
        this.homeTel = homeTel;
        this.mobileTel = mobileTel;
        this.email = email;
        this.address = address;
    }

   
    // Property accessors

    public Integer getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    public Integer getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    public Integer getTeacherTypeId() {
        return this.teacherTypeId;
    }
    
    public void setTeacherTypeId(Integer teacherTypeId) {
        this.teacherTypeId = teacherTypeId;
    }

    public String getDutyTechnicalPost() {
        return this.dutyTechnicalPost;
    }
    
    public void setDutyTechnicalPost(String dutyTechnicalPost) {
        this.dutyTechnicalPost = dutyTechnicalPost;
    }

    public byte getIsRetire() {
        return this.isRetire;
    }
    
    public void setIsRetire(byte isRetire) {
        this.isRetire = isRetire;
    }

    public float getMoney() {
        return this.money;
    }
    
    public void setMoney(float money) {
        this.money = money;
    }

    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    public String getPersition() {
        return this.persition;
    }
    
    public void setPersition(String persition) {
        this.persition = persition;
    }

    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    public String getFirstchar() {
        return this.firstchar;
    }
    
    public void setFirstchar(String firstchar) {
        this.firstchar = firstchar;
    }

    public String getOrganTel() {
        return this.organTel;
    }
    
    public void setOrganTel(String organTel) {
        this.organTel = organTel;
    }

    public String getHomeTel() {
        return this.homeTel;
    }
    
    public void setHomeTel(String homeTel) {
        this.homeTel = homeTel;
    }

    public String getMobileTel() {
        return this.mobileTel;
    }
    
    public void setMobileTel(String mobileTel) {
        this.mobileTel = mobileTel;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
   








}