package com.talent.hibernate;

import java.util.Date;


/**
 * TeachingPlanUnit generated by MyEclipse - Hibernate Tools
 */

public class TeachingPlanUnit  implements java.io.Serializable {


    // Fields    

     private Integer unitId;
     private Integer classId;
     private Integer planId;
     private String unitName;
     private String unitTitle;
     private String scoringMethod;
     private String department;
     private String principal;
     private Date beginTime;
     private Date endTime;
     private String demand;
     private Integer classHour;
     private Integer credit;


    // Constructors

    /** default constructor */
    public TeachingPlanUnit() {
    }

    
    /** full constructor */
    public TeachingPlanUnit(Integer classId, Integer planId, String unitName, String unitTitle, String scoringMethod, String department, String principal, Date beginTime, Date endTime, String demand, Integer classHour, Integer credit) {
        this.classId = classId;
        this.planId = planId;
        this.unitName = unitName;
        this.unitTitle = unitTitle;
        this.scoringMethod = scoringMethod;
        this.department = department;
        this.principal = principal;
        this.beginTime = beginTime;
        this.endTime = endTime;
        this.demand = demand;
        this.classHour = classHour;
        this.credit = credit;
    }

   
    // Property accessors

    public Integer getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }

    public Integer getClassId() {
        return this.classId;
    }
    
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    public Integer getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    public String getUnitName() {
        return this.unitName;
    }
    
    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    public String getUnitTitle() {
        return this.unitTitle;
    }
    
    public void setUnitTitle(String unitTitle) {
        this.unitTitle = unitTitle;
    }

    public String getScoringMethod() {
        return this.scoringMethod;
    }
    
    public void setScoringMethod(String scoringMethod) {
        this.scoringMethod = scoringMethod;
    }

    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }

    public String getPrincipal() {
        return this.principal;
    }
    
    public void setPrincipal(String principal) {
        this.principal = principal;
    }

    public Date getBeginTime() {
        return this.beginTime;
    }
    
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public String getDemand() {
        return this.demand;
    }
    
    public void setDemand(String demand) {
        this.demand = demand;
    }

    public Integer getClassHour() {
        return this.classHour;
    }
    
    public void setClassHour(Integer classHour) {
        this.classHour = classHour;
    }

    public Integer getCredit() {
        return this.credit;
    }
    
    public void setCredit(Integer credit) {
        this.credit = credit;
    }
   








}