package com.talent.hibernate;

import java.sql.Blob;
import java.util.Date;


/**
 * Thesis generated by MyEclipse - Hibernate Tools
 */

public class Thesis  implements java.io.Serializable {


    // Fields    

     private Integer thesisId;
     private Integer studentId;
     private String thesisTitle;
     private Blob thesisContent;
     private Date commitTime;
     private String score;
     private Integer teacherId;
     private String teacherName;
     private Date gradeDate;
     private String remark;
     private String contentType;
     private Integer teachingGroupId;
     private String opinion;
     private Integer isGood;
     private String summary;
     private Integer iscooperate;
     private String cooperators;
     private Integer state;

     private String studentName;//学生姓名
     private String studentNo; //学号
     private String className;
     private String unitTitle; //教学单元名称
     private String cooperatorsName;//合写人
    // Constructors

    public String getUnitTitle() {
		return unitTitle;
	}


	public void setUnitTitle(String unitTitle) {
		this.unitTitle = unitTitle;
	}


	public String getClassName() {
		return className;
	}


	public void setClassName(String className) {
		this.className = className;
	}


	public String getStudentName() {
		return studentName;
	}


	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}


	/** default constructor */
    public Thesis() {
    }

    
    /** full constructor */
    public Thesis(Integer studentId, String thesisTitle, Blob thesisContent, Date commitTime, String score, Integer teacherId, String teacherName, Date gradeDate, String remark, String contentType, Integer teachingGroupId, String opinion, Integer isGood, String summary, Integer iscooperate, String cooperators, Integer state) {
        this.studentId = studentId;
        this.thesisTitle = thesisTitle;
        this.thesisContent = thesisContent;
        this.commitTime = commitTime;
        this.score = score;
        this.teacherId = teacherId;
        this.teacherName = teacherName;
        this.gradeDate = gradeDate;
        this.remark = remark;
        this.contentType = contentType;
        this.teachingGroupId = teachingGroupId;
        this.opinion = opinion;
        this.isGood = isGood;
        this.summary = summary;
        this.iscooperate = iscooperate;
        this.cooperators = cooperators;
        this.state = state;
    }

   
    // Property accessors

    public Integer getThesisId() {
        return this.thesisId;
    }
    
    public void setThesisId(Integer thesisId) {
        this.thesisId = thesisId;
    }

    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    public String getThesisTitle() {
        return this.thesisTitle;
    }
    
    public void setThesisTitle(String thesisTitle) {
        this.thesisTitle = thesisTitle;
    }

    public Blob getThesisContent() {
        return this.thesisContent;
    }
    
    public void setThesisContent(Blob thesisContent) {
        this.thesisContent = thesisContent;
    }

    public Date getCommitTime() {
        return this.commitTime;
    }
    
    public void setCommitTime(Date commitTime) {
        this.commitTime = commitTime;
    }

    public String getScore() {
        return this.score;
    }
    
    public void setScore(String score) {
        this.score = score;
    }

    public Integer getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    public String getTeacherName() {
        return this.teacherName;
    }
    
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }

    public Date getGradeDate() {
        return this.gradeDate;
    }
    
    public void setGradeDate(Date gradeDate) {
        this.gradeDate = gradeDate;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getContentType() {
        return this.contentType;
    }
    
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    public Integer getTeachingGroupId() {
        return this.teachingGroupId;
    }
    
    public void setTeachingGroupId(Integer teachingGroupId) {
        this.teachingGroupId = teachingGroupId;
    }

    public String getOpinion() {
        return this.opinion;
    }
    
    public void setOpinion(String opinion) {
        this.opinion = opinion;
    }

    public Integer getIsGood() {
        return this.isGood;
    }
    
    public void setIsGood(Integer isGood) {
        this.isGood = isGood;
    }

    public String getSummary() {
        return this.summary;
    }
    
    public void setSummary(String summary) {
        this.summary = summary;
    }

    public Integer getIscooperate() {
        return this.iscooperate;
    }
    
    public void setIscooperate(Integer iscooperate) {
        this.iscooperate = iscooperate;
    }

    public String getCooperators() {
        return this.cooperators;
    }
    
    public void setCooperators(String cooperators) {
        this.cooperators = cooperators;
    }

    public Integer getState() {
        return this.state;
    }
    
    public void setState(Integer state) {
        this.state = state;
    }


	public String getStudentNo() {
		return studentNo;
	}


	public void setStudentNo(String studentNo) {
		this.studentNo = studentNo;
	}


	public String getCooperatorsName() {
		return cooperatorsName;
	}


	public void setCooperatorsName(String cooperatorsName) {
		this.cooperatorsName = cooperatorsName;
	}
   








}