package com.talent.hibernate;

import java.util.Date;


/**
 * WorkArrange generated by MyEclipse - Hibernate Tools
 */

public class WorkArrange  implements java.io.Serializable {


    // Fields    

     private Integer arrangeId;
     private Date calendar;
     private Integer userid;
     private String beArrangedIds;
     private String tasksum;
     private String taskcontent;
     private String isremind;
     private Date awoketime;
     private String reply;
     private String haveReadIds;
     private String userName;
     private String calendarDate;
     private String type;
    // Constructors

    /** default constructor */
    public WorkArrange() {
    }

	/** minimal constructor */
    public WorkArrange(Integer arrangeId) {
        this.arrangeId = arrangeId;
    }
    
    /** full constructor */
    public WorkArrange(Integer arrangeId, Date calendar, Integer userid, String beArrangedIds, String tasksum, String taskcontent, String isremind, Date awoketime, String reply, String haveReadIds) {
        this.arrangeId = arrangeId;
        this.calendar = calendar;
        this.userid = userid;
        this.beArrangedIds = beArrangedIds;
        this.tasksum = tasksum;
        this.taskcontent = taskcontent;
        this.isremind = isremind;
        this.awoketime = awoketime;
        this.reply = reply;
        this.haveReadIds = haveReadIds;
    }

   
    // Property accessors

    public Integer getArrangeId() {
        return this.arrangeId;
    }
    
    public void setArrangeId(Integer arrangeId) {
        this.arrangeId = arrangeId;
    }

    public Date getCalendar() {
        return this.calendar;
    }
    
    public void setCalendar(Date calendar) {
        this.calendar = calendar;
    }

    public Integer getUserid() {
        return this.userid;
    }
    
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public String getBeArrangedIds() {
        return this.beArrangedIds;
    }
    
    public void setBeArrangedIds(String beArrangedIds) {
        this.beArrangedIds = beArrangedIds;
    }

    public String getTasksum() {
        return this.tasksum;
    }
    
    public void setTasksum(String tasksum) {
        this.tasksum = tasksum;
    }

    public String getTaskcontent() {
        return this.taskcontent;
    }
    
    public void setTaskcontent(String taskcontent) {
        this.taskcontent = taskcontent;
    }

    public String getIsremind() {
        return this.isremind;
    }
    
    public void setIsremind(String isremind) {
        this.isremind = isremind;
    }

    public Date getAwoketime() {
        return this.awoketime;
    }
    
    public void setAwoketime(Date awoketime) {
        this.awoketime = awoketime;
    }

    public String getReply() {
        return this.reply;
    }
    
    public void setReply(String reply) {
        this.reply = reply;
    }

    public String getHaveReadIds() {
        return this.haveReadIds;
    }
    
    public void setHaveReadIds(String haveReadIds) {
        this.haveReadIds = haveReadIds;
    }
   
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
   
    public String getCalendarDate() {
        return this.calendarDate;
    }
    
    public void setCalendarDate(String calendarDate) {
        this.calendarDate = calendarDate;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }






}