 <object id=MIDIPlayer 
                  codebase=http://activex.microsoft.com/activex/controls/mplayer/en/nsmp2inf.cab#Version=5,1,52,701 
                  type=application/x-oleobject height=0 
                  standby="?? Microsoft Windows Media Player ??..." width=0 
                  classid=CLSID:22D6F312-B0F6-11D0-94AB-0080C74C7E95 
                  name=wmplayer VIEWASTEXT>
                                <param name="FileName" valuetalent//page//park//wav//3.wav>
                                <param name="AutoStart" value="true">
                                <param name="AutoRewind" value="-1">
                                <param name="AnimationAtStart" value="true">
                                <param name="ShowControls" value="false">
                                <param name="ClickToPlay" value="false">
                                <param name="EnableContextMenu" value="true">
                                <param name="EnablePositionControls" value="false">
                                <param name="Balance" value="0">
                                <param name="ShowStatusBar" value="false">
                                <param name="AutoSize" value="0">
                                <embed type="application/x-mplayer2" 
                  pluginspage="http://www.microsoft.com/Windows/Downloads/Contents/Products/MediaPlayer/" 
                  filename src  autostart="false" enablecontextmenu="false" 
                  clicktoplay="false" enablepositioncontrols="false" 
                  showcontrols="0" showstatusbar="1" showdisplay="0"> </embed> 
 </object> 